### ISSUE TITLE
cannot pip install the latest ipyvuetify version

### ISSUE THREAD

**Issue by 12rambau** [widgetti/ipyvuetify#256]
@maartenbreddels, I just tested the `nox` branch since you merged the isolation build and the `generate_source` file is missing. leading to the following error:

```
ModuleNotFoundError: No module named 'generate_source'
```

It can be reproduced locally super easilly: 

```
pip install git+https://github.com/widgetti/ipyvuetify.git
```

That emphasis again the need for some build test action (my next PR once the nox one becomes operational)

**Comment by maartenbreddels** [comment]
Super strange, because that was what I was doing in https://github.com/widgetti/ipyvuetify/pull/254/files  I thought.
Thanks for reporting, we really want to get this sorted out, and https://github.com/widgetti/solara/pull/67 should ensure we will never release non-funtional releases anymore.
If you know how to fix this, help is welcome!

**Comment by maartenbreddels** [comment]
So, currently, our release should be failure proof, we do visual tests before we distribute. Now we can safely experiment and try to fix this. 

I think currently in CI this doesn't fail because we first run: https://github.com/widgetti/ipyvuetify/blob/f4937c0919ffd370de37700ecb6afb1f68bcf094/.github/workflows/test.yml#L32

I think the way forward is to remove that line, and somehow get it to work.

**Comment by 12rambau** [comment]
I'm working on it from a branch on my side. Many things from setup.py are now deprecated in setuptools. If you want I can make a draft PR so you see where I stand.

**Comment by maartenbreddels** [comment]
Yeah, we can now totally rely on CI I think. So that might also be a good test run.

**Comment by 12rambau** [comment]
I just read the test and there are 3 ways of building the lib. I think we should stick to `python -m pip install .` in order to mimick how people are installing it on their side.
for the release process `python -m build` is the way to go.
